UN2008e0M <- read.delim(file='UN2008e0M.txt', comment.char='#')
# change the column names from the ones generated by R (X2000.2005) to the original ones (2000-2005)
get.new.e0.colnames <- function() {
        ncols <- ncol(UN2008e0M)
        colnames.years <- colnames(UN2008e0M)[4:ncols]
        colnames(UN2008e0M)[4:ncols] <- substr(colnames.years, 2, 10)
        substr(colnames(UN2008e0M)[4:ncols], 5,5) <- '-'
        return(colnames(UN2008e0M))
}
colnames(UN2008e0M) <- get.new.e0.colnames()
